name: build and release

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get repo files
        uses: actions/checkout@v4
      - name: Configure build directory
        run: cmake -H. -B build
      - name: Build project
        run: cmake --build build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Applications
          path: |
            ./build/solver_application/solver_app

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Applications
          path: ./apps
      - name: Fix permissions
        run: chmod +x ./apps/solver_app
      - name: Test solver
        run: echo "1 5 -6" | ./apps/solver_app

  create-binary-packages:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Get repo files
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm
      - name: Configure build directory
        run: cmake -H. -B build
      - name: Build project
        run: cmake --build build --config Release
      - name: Create packages
        run: |
          cd build
          cpack -G DEB -C Release
          cpack -G RPM -C Release
          cpack -G TGZ -C Release
      - name: Upload binary packages
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.deb
            build/*.rpm
            build/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
