name: C++ CI with Tests and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: sudo apt-get install -y lcov gcovr
    
    - name: Configure CMake with coverage
      run: cmake -H. -B build -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON
    
    - name: Build
      run: cmake --build build
    
    - name: Run tests (generates .gcda files)
      run: |
        cd build
        ctest --output-on-failure
        ls -la  # Проверяем, создались ли .gcda файлы
    
    - name: Generate coverage report
      run: |
        cd build
        # Находим все .gcda файлы
        find . -name "*.gcda" -type f
        # Генерируем отчёт
        lcov --capture --directory . --output-file coverage.info --no-external --ignore-errors empty
        lcov --remove coverage.info '/usr/*' '*/third-party/*' '*/tests/*' --output-file coverage.info --ignore-errors empty
        lcov --list coverage.info
    
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        file: build/coverage.info
        format: lcov
        github-token: ${{ secrets.GITHUB_TOKEN }}
